# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
