# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_of_the_posting',
        ),
    ]
